data:
  registries.conf: |
    registries:
      - name: ECR
        api-url: https://484907514740.dkr.ecr.ap-southeast-1.amazonaws.com
        prefix: 484907514740.dkr.ecr.ap-southeast-1.amazonaws.com
        credentials: ext:/scripts/ecr-login.sh


spec:
  template:
    spec:
      containers:
        - name: argocd-image-updater
          volumeMounts:
            - name: ecr-script
              mountPath: /scripts/ecr-login.sh
              subPath: ecr-login.sh
      volumes:
        - name: ecr-script
          configMap:
            name: ecr-login-script
            defaultMode: 0755