#apiVersion: v1 
#kind: Secret 
#metadata: 
#  name: grafana-cloud 
#  namespace: monitoring 
#stringData: 
#  prometheus-host: <prometheus host> 
#  prometheus-username: <prometheus username> 
#  prometheus-password: <prometheus password> 
#  loki-host: <loki host> 
#  loki-username: <loki username> 
#  loki-password: <loki password> 
#  tempo-host: <tempo host> 
#  tempo-username: <tempo username> 
#  tempo-password: <tempo password> 


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-grafana
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/group.name: shared-backend-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
    - host: grafana.myomins.website
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
